import { env } from '@/config/env';

export const CACHE_TTL = {
  RESUME_ENHANCE_SECONDS: env.CACHE_TTL_RESUME_ENHANCE_SECONDS,
  ATS_SCORE_SECONDS: env.CACHE_TTL_ATS_SCORE_SECONDS,
  KEYWORD_EXTRACTION_SECONDS: env.CACHE_TTL_KEYWORD_EXTRACTION_SECONDS,
} as const;
