import { env } from '@/config/env';

export const CACHE = {
  NAMESPACE: env.CACHE_NAMESPACE,
  REDIS_RECONNECT_MAX_RETRIES: env.REDIS_RECONNECT_MAX_RETRIES,
  REDIS_RECONNECT_BASE_DELAY_MS: env.REDIS_RECONNECT_BASE_DELAY_MS,
  REDIS_RECONNECT_MAX_DELAY_MS: env.REDIS_RECONNECT_MAX_DELAY_MS,
} as const;
