import { env } from '@/config/env';

export const PAGINATION = {
  DEFAULT_PAGE: env.PAGINATION_DEFAULT_PAGE,
  DEFAULT_LIMIT: env.PAGINATION_DEFAULT_LIMIT,
  DEFAULT_LIMIT_FALLBACK: env.PAGINATION_DEFAULT_LIMIT_FALLBACK,
  MAX_LIMIT: env.PAGINATION_MAX_LIMIT,
  SERVICE_MAX_LIMIT: env.PAGINATION_SERVICE_MAX_LIMIT,
  DEFAULT_SORT_ORDER: env.PAGINATION_DEFAULT_SORT_ORDER,
} as const;
