import { ResumeTemplate } from '@/types/resume';

export const resumeTemplates: ResumeTemplate[] = [
  {
    id: 'simple-professional',
    name: 'Professional',
    description: 'Clean single-column layout trusted for corporate, banking, and general applications. ATS-friendly by design.',
    category: 'classic',
    colors: { primary: '#1e293b', secondary: '#ffffff', accent: '#3b82f6' },
    layout: 'single-column',
    features: ['ATS Optimized', 'Clean & Readable', 'Universal Fit'],
  },
  {
    id: 'harvard',
    name: 'Harvard Classic',
    description: 'Centered header with serif typography and ruled sections — the gold standard for consulting, finance, and MBA applications.',
    category: 'classic',
    colors: { primary: '#1a1a1a', secondary: '#ffffff', accent: '#1a1a1a' },
    layout: 'single-column',
    features: ['Consulting Standard', 'Academic Prestige', 'ATS Safe'],
  },
  {
    id: 'ats-classic',
    name: 'ATS Classic',
    description: 'Maximally ATS-compatible. No tables, no graphics — pure text structure that passes every parser without losing a point.',
    category: 'classic',
    colors: { primary: '#111827', secondary: '#ffffff', accent: '#1d4ed8' },
    layout: 'single-column',
    features: ['Highest ATS Score', 'No Graphics', 'Parser-Safe'],
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Ultra-clean whitespace-first design. Lets your content breathe — ideal when your work speaks for itself.',
    category: 'minimal',
    colors: { primary: '#111827', secondary: '#ffffff', accent: '#374151' },
    layout: 'single-column',
    features: ['Whitespace Focus', 'Timeless Style', 'High Readability'],
  },
  {
    id: 'clean-pro',
    name: 'Clean Pro',
    description: 'Bold gradient header accent with generous whitespace and crystal-clear section hierarchy.',
    category: 'minimal',
    colors: { primary: '#0f172a', secondary: '#ffffff', accent: '#6366f1' },
    layout: 'two-column',
    features: ['High Contrast', 'Strong Hierarchy', 'Modern & Clean'],
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional serif resume with time-tested formatting. Conservative and professional for law, government, and finance roles.',
    category: 'classic',
    colors: { primary: '#1e293b', secondary: '#ffffff', accent: '#64748b' },
    layout: 'single-column',
    features: ['Serif Typography', 'Conservative', 'Universally Accepted'],
  },
  {
    id: 'tech',
    name: 'Tech Engineer',
    description: 'Dark left sidebar with skill stack visualization and a crisp right panel. Designed specifically for software engineers and developers.',
    category: 'modern',
    colors: { primary: '#0f172a', secondary: '#f8fafc', accent: '#0ea5e9' },
    layout: 'sidebar',
    features: ['Skills Sidebar', 'GitHub-Friendly', 'Tech-Focused'],
  },
  {
    id: 'sidebar',
    name: 'Sidebar',
    description: 'Efficient two-column layout with a clean sidebar for contact info and skills, freeing the main column for experience.',
    category: 'modern',
    colors: { primary: '#1f2937', secondary: '#f3f4f6', accent: '#4b5563' },
    layout: 'sidebar',
    features: ['Space-Efficient', 'Two-Column', 'Easy to Scan'],
  },
  {
    id: 'two-column',
    name: 'Two-Column',
    description: 'Structured dual-column layout that separates primary experience from supporting details — ideal for mid to senior profiles.',
    category: 'modern',
    colors: { primary: '#0f172a', secondary: '#f8fafc', accent: '#2563eb' },
    layout: 'sidebar',
    features: ['Clear Hierarchy', 'Organized Sections', 'Scannable'],
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'Playfair Display serif headings with a gold accent stripe and elegant dot-rated language section. Commands attention for senior roles.',
    category: 'classic',
    colors: { primary: '#1a2b3c', secondary: '#ffffff', accent: '#c8a97e' },
    layout: 'sidebar',
    features: ['Elegant Typography', 'Premium Feel', 'Senior Leadership'],
  },
  {
    id: 'bold-leader',
    name: 'Bold Leader',
    description: 'High-impact dark header with a commanding accent strip. Makes an immediate visual impression for VP, Director, and C-suite roles.',
    category: 'modern',
    colors: { primary: '#111827', secondary: '#ffffff', accent: '#dc2626' },
    layout: 'two-column',
    features: ['Executive Impact', 'Bold Typography', 'Authority Presence'],
  },
  {
    id: 'modern',
    name: 'Modern Dark',
    description: 'Dark-mode canvas with indigo accents and card-based sections. Stands out in creative, startup, and product roles.',
    category: 'modern',
    colors: { primary: '#2563eb', secondary: '#ffffff', accent: '#f97316' },
    layout: 'two-column',
    features: ['Dark Theme', 'Card Layout', 'Bold & Distinctive'],
  },
  {
    id: 'creative',
    name: 'Creative Designer',
    description: 'Vibrant asymmetric layout with an accent sidebar and visual hierarchy built for designers, art directors, and creative professionals.',
    category: 'creative',
    colors: { primary: '#0f172a', secondary: '#ffffff', accent: '#6366f1' },
    layout: 'sidebar',
    features: ['Portfolio-Ready', 'Unique Layout', 'Strong Visual Impact'],
  },
  {
    id: 'europass',
    name: 'Europass',
    description: 'EU standard CV format with structured two-column rows and a dark header banner. Required for European job markets and academia.',
    category: 'classic',
    colors: { primary: '#003399', secondary: '#ffffff', accent: '#003399' },
    layout: 'single-column',
    features: ['EU Standard', 'Government-Ready', 'Academic Institutions'],
  },
];

export const getTemplateById = (id: string): ResumeTemplate | undefined =>
  resumeTemplates.find((t) => t.id === id);

export const getTemplatesByCategory = (category: ResumeTemplate['category']): ResumeTemplate[] =>
  resumeTemplates.filter((t) => t.category === category);
